// WordPress webpack config.
const defaultConfig = require("@wordpress/scripts/config/webpack.config");

// Plugins.
const RemoveEmptyScriptsPlugin = require("webpack-remove-empty-scripts");

// Utilities.
const path = require("path");

// Add any new entry points by extending the webpack config.
module.exports = {
  ...defaultConfig,
  ...{
    entry: {
      "js/main": path.resolve(process.cwd(), "src/js", "main.js"),
      "js/neighborhood": path.resolve(process.cwd(), "src/js", "neighborhood.js"),
      //"js/editor": path.resolve(process.cwd(), "src/js", "editor.js"),
      "css/main": path.resolve(process.cwd(), "src/scss", "main.scss"),
      "css/editor": path.resolve(process.cwd(), "src/scss", "editor.scss"),
    },
    module: {
      rules: [
        // Use Webpack's built-in asset module for images (Webpack 5)
        {
          test: /\.(jpg|jpeg|png|gif|svg)$/i, // Image file types
          type: 'asset/resource', // Asset module (new in Webpack 5)
          generator: {
            filename: 'images/[name][ext][query]', // Store images in 'images' folder with original name and extension
          },
        },
        // Add any other rules you may already have, if necessary
        ...defaultConfig.module.rules,
      ],
    },
    plugins: [
      // Include WP's plugin config.
      ...defaultConfig.plugins,

      // Removes the empty `.js` files generated by webpack but
      // sets it after WP has generated its `*.asset.php` file.
      new RemoveEmptyScriptsPlugin({
        stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
      }),
    ],
  },
};

